baseURL: "https://econsbaum.github.io/" #"https://www.example.com/"
#theme: "up-business-theme"
languageCode: "es"

title: "Econsbaum"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Econsbaum"
  description: "Ingeniería y Consultoría"
  images: 
    - "images/hero-image.png"

  logo: "images/logo-econsbaum.png"
  #"arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "https://www.facebook.com/econsbaum/"
    twitter: "#"

  location:
    - "Calle Pedro Salazar No. 627 Zona Sopocachi (Cerca AJAM)"

  contact:
    - "econsbaum@gmail.com"
    - "(591)-70170096  (591)-71220431"

  copyright: "© 2024 Econsbaum All Rights Reserved"

menus:
  main:
    - name: "Mineria"
      url: "/mineria"
      weight: 1

    - name: "Industria"
      url: "/industria"
      weight: 2

    - name: "Capacitaciones"
      url: "/capacitaciones"
      weight: 3

    - name: "Construcción"
      url: "/construccion"
      weight: 4

    # - name: "Videos"
    #   url: "/post"
    #   weight: 5

  buttons:
    - name: "Contactenos"
      url: "https://wa.me/59170170096?text=Buenos%dias%quisiera%informacion%acerca%de%sus%servicios%en%Econsbaum"
      weight: 6
      pre: "btn btn-primary text-light"

  footer:
    - name: "Principal"
      url: "/#hero"
      weight: 1

    - name: "Cotice nuestros servicios"
      url: "https://wa.me/59170170096?text=Buenos%dias%Econsbaum%quisiera%una%cotizacion%de%sus%servicios"
      weight: 2

    # - name: "Our team"
    #   url: "/homepage"
    #   weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

taxonomies:
  series: "series"
  tags: "tags"
